analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3441334,"name"\:"Sample - HR Web App \#3441334","teamId"\:3414742,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3476581,"sampleProject"\:false,"autoIntegrate"\:false,"accountId"\:null}
analytics.team={"id"\:3414742,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.hub.switchHub.enable=true
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
